// User
const CANNOT_FIND_USER = 'CANNOT_FIND_USER';
const INVALID_TOKEN = 'INVALID_TOKEN';
const INVALID_SIGN_IN_USER_INFO = 'INVALID_SIGN_IN_USER_INFO';
const INVALID_SIGN_UP_USER_INFO = 'INVALID_SIGN_UP_USER_INFO';
const EMAIL_EXISTED = 'EMAIL_EXISTED';
const INVALID_OBJECT_ID = 'INVALID_OBJECT_ID';
//Story
const INVALID_STORY_INFO = 'INVALID_STORY_INFO';
const CANNOT_FIND_STORY = 'CANNOT_FIND_STORY';
//Comment
const INVALID_COMMENT = 'INVALID_COMMENT';
const CANNOT_FIND_COMMENT = 'CANNOT_FIND_COMMENT';
//Friend
const INVALID_FRIEND_REQUEST = 'INVALID_FRIEND_REQUEST';
module.exports = {
    CANNOT_FIND_USER,
    INVALID_TOKEN,
    INVALID_SIGN_IN_USER_INFO,
    INVALID_SIGN_UP_USER_INFO,
    EMAIL_EXISTED,
    INVALID_STORY_INFO,
    INVALID_OBJECT_ID,
    CANNOT_FIND_STORY,
    INVALID_COMMENT,
    CANNOT_FIND_COMMENT,
    INVALID_FRIEND_REQUEST
};
